# Site settings
title: EOfarm
email: info@eofarm.com
description: > # this means to ignore newlines until "baseurl:"
  We are cultivating Big Earth Observation Data, offering cutting-edge
  Geospatial Services.
keywords: > # this means to ignore newlines until "baseurl:"
  earth observation, precision agriculture, water quality, monitoring, 
  big data, data analysis, maps, time series, geospatial applications
baseurl: "http://eofarm.com/" # the subpath of your site, e.g. /blog/
url: "http://locahost:4000" # the base hostname & protocol for your site
github_username:  EOFarm

# Build settings
regeneration: -w
markdown: kramdown
